// <auto-generated />
using System;
using Car_Rental.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car_Rental.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240610000629_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car_Rental.Models.Admin", b =>
                {
                    b.Property<int>("Admins_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Admins_ID"));

                    b.Property<string>("CreateLogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatePassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sales")
                        .HasColumnType("int");

                    b.HasKey("Admins_ID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Car_Rental.Models.Car", b =>
                {
                    b.Property<int>("Cars_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cars_ID"));

                    b.Property<bool?>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Cars_ID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Car_Rental.Models.Card", b =>
                {
                    b.Property<int>("Cards_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cards_ID"));

                    b.Property<byte>("Cashback")
                        .HasColumnType("tinyint");

                    b.Property<int>("Customers_ID")
                        .HasColumnType("int");

                    b.Property<long>("Payment")
                        .HasColumnType("bigint");

                    b.Property<long>("Points")
                        .HasColumnType("bigint");

                    b.HasKey("Cards_ID");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Car_Rental.Models.Contract", b =>
                {
                    b.Property<int>("Contracts_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Contracts_ID"));

                    b.Property<int>("Cards_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Customers_ID")
                        .HasColumnType("int");

                    b.Property<string>("DocumentLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Contracts_ID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Car_Rental.Models.Customer", b =>
                {
                    b.Property<int>("Customers_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Customers_ID"));

                    b.Property<bool>("ActiveRent")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Customers_ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Car_Rental.Models.Discount", b =>
                {
                    b.Property<int>("Discounts_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Discounts_ID"));

                    b.Property<int>("Cars_ID")
                        .HasColumnType("int");

                    b.Property<byte>("NewPrice")
                        .HasColumnType("tinyint");

                    b.HasKey("Discounts_ID");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Car_Rental.Models.Rent", b =>
                {
                    b.Property<int>("Rent_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rent_ID"));

                    b.Property<int>("Cars_ID")
                        .HasColumnType("int");

                    b.Property<int>("Customers_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Rent_ID");

                    b.ToTable("Rents");
                });

            modelBuilder.Entity("Car_Rental.Models.ServiceDate", b =>
                {
                    b.Property<int>("ServiceDate_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceDate_ID"));

                    b.Property<int>("Cars_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NextDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PreviousDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ServiceDate_ID");

                    b.ToTable("ServicesDates");
                });
#pragma warning restore 612, 618
        }
    }
}
